services:
  mimir:
    image: grafana/mimir:2.12.0
    container_name: mimir
    ports:
      - 9090:9090
    restart: unless-stopped
    command: --config.file=/etc/mimir.yaml
    volumes:
      - ./services/mimir/mimir.yaml:/etc/mimir.yaml
      - ./services/mimir/alertmanager.yaml:/etc/alertmanager-fallback-config.yaml
 
  loki:
    image: grafana/loki:3.1.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      - JAEGER_AGENT_HOST=otelcol

  grafana:
    image: grafana/grafana:11.0.1
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - ./services/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      # - ./services/grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - loki
      - tempo
      - mimir

  tempo:
    image: grafana/tempo:2.5.0
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./services/tempo/tempo.yaml:/etc/tempo.yaml

  ## Tools
  promtail:
    image: grafana/promtail:2.9.5
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml

  otelcol:
    image: otel/opentelemetry-collector:0.104.0
    container_name: otelcol
    # restart: unless-stopped
    ports:
      - 4317:4317  # otlp grpc
      - 4318:4318  # otlp http
      - 8888:8888 # monitoring
    command: --config=/etc/otelcol/config.yaml
    depends_on:
      - loki
      - tempo
      - mimir
      - grafana
    volumes:
      - ./services/otelcol/config.yaml:/etc/otelcol/config.yaml
